[2024-11-20T23:20:22.890+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: principal_to_stage.load_incremental_data_vendas scheduled__2024-11-19T23:20:13.214210+00:00 [queued]>
[2024-11-20T23:20:22.907+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: principal_to_stage.load_incremental_data_vendas scheduled__2024-11-19T23:20:13.214210+00:00 [queued]>
[2024-11-20T23:20:22.908+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-20T23:20:22.909+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-11-20T23:20:22.909+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-20T23:20:22.932+0000] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): load_incremental_data_vendas> on 2024-11-19 23:20:13.214210+00:00
[2024-11-20T23:20:22.940+0000] {standard_task_runner.py:55} INFO - Started process 177 to run task
[2024-11-20T23:20:22.946+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'principal_to_stage', 'load_incremental_data_vendas', 'scheduled__2024-11-19T23:20:13.214210+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/extract_to_stage_dag.py', '--cfg-path', '/tmp/tmp7yvykwvg']
[2024-11-20T23:20:22.947+0000] {standard_task_runner.py:83} INFO - Job 82: Subtask load_incremental_data_vendas
[2024-11-20T23:20:23.049+0000] {task_command.py:388} INFO - Running <TaskInstance: principal_to_stage.load_incremental_data_vendas scheduled__2024-11-19T23:20:13.214210+00:00 [running]> on host 7d17ca507f32
[2024-11-20T23:20:23.190+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=principal_to_stage
AIRFLOW_CTX_TASK_ID=load_incremental_data_vendas
AIRFLOW_CTX_EXECUTION_DATE=2024-11-19T23:20:13.214210+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-11-19T23:20:13.214210+00:00
[2024-11-20T23:20:23.205+0000] {base.py:73} INFO - Using connection ID 'novadrive-principal' for task execution.
[2024-11-20T23:20:24.529+0000] {base.py:73} INFO - Using connection ID 'novadrive-stage' for task execution.
[2024-11-20T23:20:24.756+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_to_stage_dag.py", line 51, in load_incremental_data
    stage_cursor.execute(insert_query, row)
psycopg2.errors.ForeignKeyViolation: ERRO:  inserção ou atualização em tabela "vendas" viola restrição de chave estrangeira "vendas_id_clientes_fkey"
DETAIL:  Chave (id_clientes)=(144956) não está presente na tabela "clientes".

[2024-11-20T23:20:24.771+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=principal_to_stage, task_id=load_incremental_data_vendas, execution_date=20241119T232013, start_date=20241120T232022, end_date=20241120T232024
[2024-11-20T23:20:24.789+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 82 for task load_incremental_data_vendas (ERRO:  inserção ou atualização em tabela "vendas" viola restrição de chave estrangeira "vendas_id_clientes_fkey"
DETAIL:  Chave (id_clientes)=(144956) não está presente na tabela "clientes".
; 177)
[2024-11-20T23:20:24.808+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-11-20T23:20:24.856+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
